version: '3.8'

services:
  blazor-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ship-ses-extractor-ui
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    volumes:
      # Optional: Mount appsettings for configuration overrides
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
    restart: unless-stopped